config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
            registrations: 'users/registrations'
        }
    get '/' => 'cities#index'
    get '/profile' => 'users#show'

    # cities
    resources :cities do
        resources :posts
    end

    root to: "cities#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts
  has_many :users, through: :posts
end

app/models/post.rb
class Post < ApplicationRecord
  # include ActiveModel::ForbiddenAttributesProtection

  belongs_to :city
  belongs_to :user
  validates :content, presence: true
  validates :title, length: {in: 1..200}, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :cities, through: :posts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @posts = @city.posts
  end

  def posts
    @posts = City.find(params[:id]).posts
    @city = City.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
     @confirm = "Are you sure you want to delete this review: #{@post.title} ?"
  end

  def edit
      @post = Post.find(params[:id])
  end

  def update
       @post = Post.find(params[:id])
       @city = City.find(params[:city_id])
       @post.update(post_params)

       redirect_to city_path(@city)
  end

  def new
    @city = City.find(params[:city_id])
    @post = Post.new
    @confirm = "You're post was submitted for #{@city.name}!"
    render :new

  end

  def create
    @city = City.find(params[:city_id])

    post = Post.create(post_params)
    city = post.city
    post.save
    if post.save
      redirect_to city_post_path(city, post)
    else
      redirect_to city_path(city)
    end

  end

  def destroy
    @city = City.find(params[:city_id])

    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "'#{@post.title}' post was deleted"
    redirect_to city_path(@city)
  end

  private
    def post_params
      params.require(:post)
        .permit(:title, :content)
        .merge(user_id: current_user.id, city_id: params[:city_id])

    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number, :first_name, :last_name, :photo_url])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo_url])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        @user = current_user
        @posts = @user.posts
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>VagabondProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
    <body>
        <div id="cf">
            <img class="cOne" src="https://source.unsplash.com/x1Qw-pfM9HA"/>
            <img class="cTwo" src="https://source.unsplash.com/QvPRGI8LfOc"/>
            <img class="cThree" src="https://source.unsplash.com/I4dPa7EVeaM"/>
            <img class="cFour" src="https://source.unsplash.com/MO-30jajbrM"/>
            <img class="cFive" src="https://source.unsplash.com/d7mKQgFYVHY"/>
        </div>

        <div class="headline">
            <h1>Welcome to your new favorite travel site!</h1>
            <h5>add your experience to a city below</h5>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="atlanta">
                        <h3>
                            <a href="/cities/<%= @cities[0].id %>" style="color: white">
                                <%= @cities[0].name %>
                            </a>
                        </h3>
                    </div>
                </div>


                <div class="col-sm-6">
                    <div class="london">
                        <h3>
                            <a href="/cities/<%= @cities[1].id %>" style="color: white">
                                <%= @cities[1].name %>
                            </a>
                        </h3>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="sanfran">
                        <h3>
                            <a href="/cities/<%= @cities[2].id %>" style="color: white">
                                <%= @cities[2].name %>
                            </a>
                        </h3>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="amsterdam">
                        <h3>
                            <a href="/cities/<%= @cities[3].id %>" style="color: white">
                                <%= @cities[3].name %>
                            </a>
                        </h3>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

app/views/cities/show.html.erb
<div class="banner" style="background: linear-gradient(rgba(255, 255, 255, 0.7),rgba(255, 255, 255, 0.7)),url(<%= @city.photo_url %>); background-position: center; background-size:cover;">
    <h1>Welcome to <%= @city.name %></h1>
</div>

<div class="row">

    <div class="col col-md-6 reviews-photo">
        <img src="<%= @city.photo_url %>" width="500px" alt="">
    </div>

    <div class="col col-md-6 reviews-show">
        <div class="border-box">
            <h2>Reviews:</h2>
                <ul>
                    <% @posts.reverse_each do |post| %>
                        <li>
                            <h4> <a href="/cities/<%= post.city_id %>/posts/<%= post.id %>"><%= post.title %></a></h4>
                            <p><%= time_ago_in_words(post.created_at)%> ago.</p>
                        </li>
                    <% end %>
                </ul>
            <br>

            <form class="add">
              <% if user_signed_in? %>
                <%= link_to "New Post", new_city_post_path(@city) %>
                <% else %>
                <% end %>
            </form>

        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Vagabond | Your Favorite Travel App</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <link rel="shortcut icon" href="app/assets/images/logo.png">

    </head>

    <nav class="row row-centered">
        <div class="col col-md-6 brand col-centered">
            <img src="http://i63.tinypic.com/2w4iss0.png" alt="Vagabond Logo" width="100px">
        </div>

        <div class="col col-md-6 main-nav col-centered">
            <ul>
                    <button class="btn btn-nav"><a href="/">Home</a></button>
                <% if user_signed_in? %>

                    <button class="btn btn-nav">
                        <%= link_to "Sign Out", destroy_user_session_path, method: "delete" %>
                    </button>

                    <button class="btn btn-nav">
                        <%= link_to "Profile", profile_path %>
                    </button>
                <% else %>

                    <button class="btn btn-nav">
                        <%= link_to "Sign Up", new_user_registration_path %>
                    </button>

                    <button class="btn btn-nav">
                        <%= link_to "Sign In", new_user_session_path %>
                    </button>

                <% end %>
            </ul>
        </div>
    </nav>


    <body>
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <%= yield %>
    </body>

    <nav class="row row-centered footer">
        <div>
          <small>Designed and Developed by <a href="http://www.matthewatkins.co">Matthew Atkins</a> and <a href="http://www.aylinmarie.co">Aylin Marie</a></small><br>
            <img src="http://i63.tinypic.com/2w4iss0.png" alt="Vagabond Logo" width="100px">

        </div>
    </nav>
</html>

app/views/posts/edit.html.erb
<h1>edit post <%= @post.title %></h1>

<%= form_for @post, url: city_post_path(id: @post.id, city_id: @post.city_id) do |f| %>
  <label>Post title:</label><br>
  <%= f.text_field :title %><br>

  <label>Post Description</label><br>
  <%= f.text_area :content %><br>

  <%= f.submit "Update" %>
<% end %>

app/views/posts/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Add New Post for <%= @city.name %> </h1>

<% if @post.errors.any? %>
    <h3>Oops there were some errors. Please try again:</h3>
        <ul>
            <% @list.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
<% end %>

<%= form_for :post, :data => {:confirm => @confirm}, url: {action: 'create'} do |f| %>
  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>

  <br>
  <%= f.label :content %> <br>
  <%= f.text_area :content %> <br>

  <%= f.submit %>
<% end %>

<hr>

app/views/posts/show.html.erb
<div class="container">
  <br>
  <h2><%= @post.title %></h2>
  <br>
  <p><%= @post.content %></p>

  <small><b>Posted: <%= time_ago_in_words(@post.created_at)%> ago by <%= @user.first_name %> <%= @user.last_name %>.</b></small> <br>
  <br>

  <a class="twitter-share-button"
  href="https://twitter.com/intent/tweet?text=Check%20out%20this%20post%20on%20Vagabond!"
  data-size="large">Tweet</a>

  <br>
  <hr>
  <% if user_signed_in? %>

  <%= link_to 'Edit', :action => 'edit', :id => @post.id %> <br>

  <%= link_to 'Delete', {:action => 'destroy', :id => @post.id}, :class => "btn btn-danger", :method => :delete, :data => {:confirm => @confirm} %>
  <% else %>
  <% end %>

  <form action="/cities/<%= @post.city_id %>">
      <input type="submit" class="btn btn-default" value="Go Back">
  </form>

</div>


<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>

app/views/users/show.html.erb
<h2 class="profile-intro">Welcome to your account <%= current_user.first_name%> !</h2>
<br>

<div class="row user-profile">
    <div class="user-information col col-md-4">
        <h4>Profile Information</h4>
        <br>
        <h6><b>Profile Image:</b><br>
        <img src="<%= current_user.photo_url %>" alt="" width="250px">
        <h6><b>Joined:<b> <%= current_user.created_at.strftime("%x") %></h6>
        <h6><b>First Name:</b> <%= current_user.first_name %></h6>
        <h6><b>Last Name:</b> <%= current_user.last_name %></h6>
        <h6><b>Email:</b> <%= current_user.email %></h6>
        <br>
        <a class="btn btn-default" href="/users/edit">EDIT ACCOUNT</a>
    </div>

    <div class="col col-md-8 user-content">
        <h4>Your posts:</h4>
        <br>
        <ul>
            <% @posts.each do |post| %>
                <h5><%= post.title %></h5>
                <li>Post: <%= post.content %></li>
                <li><small>Posted: <%= time_ago_in_words(post.created_at)%></small></li>
                <a class="btn btn-default" href="/cities/<%= post.city_id %>/posts/<%= post.id %>/edit">EDIT</a>
                <a class="btn btn-danger" href="/cities/<%= post.city_id %>/posts/<%= post.id %>">DELETE</a>
                <hr>
            <% end %>
        </ul>
    </div>
</div>